name: Release

on:
  repository_dispatch:
    types: [webhook]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Intall dependencies
        run: echo "Installing"
      - name: echo version
        run: echo ${{ github.event.client_payload.rollbackVersion }}
